Title: Oluwanifesimi Adebayo
Description: Professional Data Analyst
Logo: https://github.com/Nifemiiiiiiii/Portfolio/blob/13af30ef20384be7dd649cdd48404f0a27f2eb22/Portfolio%20pic.JPG
theme: jekyll-theme-minimal 
